#!/bin/bash
# See skript tuvastab süsteemi aja ja tervitab kasutajat nimepidi.

# Kasutaja nimi (kes on sisse loginud)
kasutaja=$USER

# Süsteemi kell (ainult tunnid, 0–23)
tund=$(date +%H)

if test $tund -ge 6 -a $tund -lt 12
then
    echo "Tere hommikust, $kasutaja!"
elif test $tund -ge 12 -a $tund -lt 18
then
    echo "Tere päevast, $kasutaja!"
elif test $tund -ge 18 -a $tund -lt 22
then
    echo "Tere õhtust, $kasutaja!"
elif test $tund -ge 22 -o $tund -lt 6
then
    echo "Head ööd, $kasutaja!"
else
    echo "Vigane süsteemi aja lugemine"
fi

