#!/bin/bash

# Skript bussiekskursioonide korraldajale
#
# reisiate arv
echo -n "Sisesta reisijate arv: "
read reisijad
# kohtade arv bussis
echo -n "Sisesta kohtade arv bussis: "
read kohad
#
# arvutused
#
# jagame inimesed busside vahel nii, et kõik kohad bussides oleks täidetud - se>
# saame teada, palju busse on vaja
bussid=$(($reisijad / $kohad))
# vaatame, palju on need, kes ei saanud koha bussides - need on üle jäänud reis>
# ehk jäägid, kui kõik kohad on täidetud
ylejaanud=$(($reisijad % $kohad))
# kui on olemas ülejäänud, tuleb suurendada busside arv 1 võrra
if test $ylejaanud -gt 0
then
    # bussid muutuja vajab üledefineerimist, selle pärast ümber salvestamiseks
    # ei kasuta $ märki, aga arvutamisel juba kasutame
    bussid=$(($bussid + 1))
fi
#
# tulemuste väljastamine
#
echo "Kokku on vaja $bussid täisbussi"
#
# skripti lõpp
