#!/bin/bash

#paarsuse kontroll
echo -n "Sisesta suvaline täisarv: " 
read arv

#arvutame 2-ga jagamine
jaak=$(( $arv % 2 ))
# 4 % 2 => 0 -> siis arv on paaris
# 5 % 2 => 1 -> siis arv on paaritu

if [ $jaak -eq 0 ]
then
    echo "$Antud arv on paaris"
else
    echo "$Antud arv on paaritu"
fi
#tingimus kontroll on lõppenud
